### ISSUE TITLE
Ingestion of half-hourly GPP data

### ISSUE THREAD

**Issue by padasch** [computationales/ingestr#35]
**Problem:**
- Ingestion of half-hourly GPP data does not work.

**Reproducible Example:**
```
library(tidyverse)
library(ingestr)

settings_fluxnet <- list(
    getswc       = FALSE,
    filter_ntdt  = TRUE,
    threshold_GPP= 0.8,
    remove_neg   = FALSE,
    dir_hh = "~/data/FLUXNET-2015_Tier1/20191024/HH/"
)

ddf_fluxnet <- ingest(
    ingestr::siteinfo_fluxnet2015 %>%  slice(1:3),
    source    = "fluxnet",
    getvars   = list(
        # temp = "TA_F",
        # prec = "P_F",
        # vpd  = "VPD_F",
        # ppfd =  "SW_IN_F",
        # netrad = "NETRAD",
        # patm = "PA_F",
        gpp = "GPP_NT_VUT_REF"
    ), 
    dir       = "~/data/FLUXNET-2015_Tier1/20191024/HH/", 
    settings  = settings_fluxnet,
    timescale = "hh",
    verbose = TRUE
)
```

**Error Message:**
- Note that to create this error message, first [this line](https://github.com/computationales/ingestr/blob/4d127d7767852bfe8a06a276bbb1431ed47eed79/R/get_obs_bysite_fluxnet.R#L1024) has to be changed to `na_if(-9999)` (depends on the tidyverse version being used).

```
Error: Problem with `mutate()` column `GPP_NT_VUT_REF`.
i `GPP_NT_VUT_REF = replace_with_na_qc(GPP_NT_VUT_REF, NEE_VUT_REF_NIGHT_QC, threshold)`.
x object 'NEE_VUT_REF_NIGHT_QC' not found
```

**What I tried:**
- I traced back the error to [this line](https://github.com/computationales/ingestr/blob/4d127d7767852bfe8a06a276bbb1431ed47eed79/R/get_obs_bysite_fluxnet.R#L1010), where the loaded file seems to not hold the variables `NEE_VUT_REF_DAY_QC` and `NEE_VUT_REF_NIGHT_QC` needed for GPP quality control later in [this line](https://github.com/computationales/ingestr/blob/4d127d7767852bfe8a06a276bbb1431ed47eed79/R/get_obs_bysite_fluxnet.R#L1108) (which prompts the error message above).
-  I am not familiar enough with the FLUXNET csv file structure and how ingestr uses them. Tying to point the code towards different files in `"~/data/FLUXNET-2015_Tier1/20191024/HH/."` did not resolve the issue.

**Comment by khufkens** [comment]
This is a bug. These values (i.e. NEE_VUT_REF_NIGHT_QC etc) do not exist in the HH product, and since routines are not yet unit tested (I'm still implementing this step by step) this wasn't caught during development as it hasn't been used (it seems) until you did. Just to demonstrate why you need unit tests.

Will look into this further tomorrow.

**Comment by khufkens** [comment]
Ok verified here: https://fluxnet.org/data/fluxnet2015-dataset/fullset-data-product/

NEE_VUT_REF_NIGHT_QC is not produced. So can't be used for HH here: 
https://github.com/computationales/ingestr/blob/4d127d7767852bfe8a06a276bbb1431ed47eed79/R/get_obs_bysite_fluxnet.R#L1108

@stineb what is the proposed solution for screening HH for QC

**Comment by stineb** [comment]
There must be a confusion. 

The variable `NEE_VUT_REF_NIGHT` is average _nighttime_ NEE. It's probably not in the HH dataset since it doesn't make sense.

We want to use `NEE_VUT_REF`.  And the corresponding QC flag is `NEE_VUT_REF_QC`. Note that it's not a fraction as for other time scales, but a categorical value with 0 = measured, 1 = good quality gapfilled, 2 = medium, 3 = poor. 

See file `~/data/FLUXNET-2015_Tier1/doc/variable_codes_FULLSET_20160711.pdf`.

**Comment by khufkens** [comment]
Fixed per https://github.com/computationales/ingestr/commit/790afc5eba51393d2d4c7308a655d0b0098bc173
